praktikum 15
ackudryavcev/YProject15n.github.io pull request #1
Opened 2020-02-11 12:49 UTC by ackudryavcev

Проектная работа 15

2020-02-11 15:15 UTC, zlocate requested changes
Хороша, качественная работа. Было приятно проверять :) 
Чуть больше внимания к мелочам и ошибкам линтера и успех обеспечен.

Порадовало разумное и уместное использование синтаксиса ES6 (декструктуризации, значений по-умолчанию), а также использование популярных и обкатанных решений для логирования и валидации.

Надеюсь, мои комментарии "можно лучше" не смутят вас :)

Работа будет принята после исправления следующих ошибок:
0. Домен ведет на фронтенд сервис, а не на бекенд. Просьба исправить
1. ENV файлы, особенно содержащие критичные параметры вроде секретов и авторизационных данных не должны попадать в репозиторий
2. Обработка ошибок должна быть централизованной. Валидация должна проходить уровнем выше
3. При запуске при помощи npm start процесс запускается непосредственно интерпретатором nodejs и после обращения по данному URL сервис падает и не поднимается автоматически.
4. Обработка ошибок должна быть централизованной. Валидация должна проходить уровнем выше
константа validator не используется.
5. Попытка обращения к методу validate.isUrl() который не определен (см комментарий выше)

2020-02-11 15:15 UTC, zlocate commented on app.js
> +const { PORT = 3000 } = process.env;
Отлично: Отличный вариант применения дестуктуризации 👍

2020-02-11 15:15 UTC, zlocate commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Можно лучше:  
1) при работе с боевыми сервисами база данных нередко находится на отдельном узле\внешнем сервисе поэтому полезно при запуске в боевому окружении подгружать путь до БД из ENV.
2) В случае недоступности базы данных произойдет ошибка которая не будет обработана

2020-02-11 15:15 UTC, zlocate commented on app.js
> +// eslint-disable-next-line no-unused-vars
Отлично: использование правил-исключений для линтера позволяет снизить число ложных срабатываний +1

2020-02-11 15:15 UTC, zlocate commented on app.js
> +app.listen(PORT, () => {
Можно лучше:
    Желательно обрабатывать ошибку, когда порт недоступен и завершать работу приложения
    Это может произойти при запуске нескольких экземляров приложения, 
    либо если несколько сервисов на одной машине попытаются использовать один порт

2020-02-11 15:15 UTC, zlocate commented on README.md
> +* все запросы и ответы записываются в файл request.log;
Можно лучше: тело ответа не всегда записывается в лог-файл

2020-02-11 15:15 UTC, zlocate commented on app.js
> +require('dotenv').config();
Отлично: Хорошее решение. Возможно покажется интересным паттерн, предложенный данным модулем, часто используемый на практике
https://www.npmjs.com/package/dotenv-flow

2020-02-11 15:15 UTC, zlocate commented on app.js
> +app.get('/crash-test', () => {
Нужно исправить: При запуске при помощи `npm start` процесс запускается непосредственно интерпретатором nodejs и после обращения по данному URL сервис падает и не поднимается автоматически.
Сделать это можно при помощи pm2 (nodemon рекомендуется использовать только на dev-окружении)

2020-02-11 15:15 UTC, zlocate commented on app.js
> +app.use(helmet());
Отлично: Helmet даже с дефолтными настройками проставляет адекватно основные Secure-поля.

2020-02-11 15:15 UTC, zlocate commented on models/card.js
> +const validator = require('validator');
Нужно исправить: константа validator не используется.

2020-02-11 15:15 UTC, zlocate commented on models/card.js
> +const validator = require('validator');
Исходя из реализации ниже (используется метод validate.isURL(v),  при том что validate не определен делаю предположение что допущена опечатка

2020-02-11 15:15 UTC, zlocate commented on models/card.js
> +      validator: (v) => validate.isURL(v),
Нужно исправить: Попытка обращения к методу validate.isUrl()  который не определен (см комментарий выше)

2020-02-11 15:15 UTC, zlocate commented on routes/cards.js
> +    id: Joi.string().alphanum(),
Можно лучше: В качестве параметра для метода передается MongoDB ObjectId, соответственно можно более строго валидировать, например при помощи mongoose.Types.ObjectId.isValid или даже
https://www.npmjs.com/package/joi-objectid

2020-02-11 15:15 UTC, zlocate commented on package.json
> +    "path": "^0.12.7",
Нужно исправить: данный модуль не используется

2020-02-11 15:15 UTC, zlocate commented on doteenv.env
> +NODE_ENV=production
Нужно исправить: ENV файлы, особенно содержащие критичные параметры вроде секретов и авторизационных данных не должны попадать в репозиторий

2020-02-11 15:15 UTC, zlocate commented on errors/500-err.js
> +class Error500 extends Error {
Можно лучше: остальные ошибки названы по типу Auth\NotFound, эта же названа по статус-коду. 
Понимаю, что в голове стойкая ассоциация 500й код = внутренняя ошибка. Однако здесь лучше подойдет InternalServiceError

2020-02-11 15:15 UTC, zlocate commented on middlewares/auth.js
> +// eslint-disable-next-line consistent-return
👍

2020-02-11 15:15 UTC, zlocate commented on controllers/cards.js
> +        const notCardOwner = new Error('Карта не ваша! Удалить нельзя!');
Можно лучше: Возможно создание CustomError расширяющего базовый класс ошибки и принимающий в конструктор вторым параметром код ошибки будет более удобно.  Однако и данный подход применим

2020-02-11 15:15 UTC, zlocate commented on controllers/users.js
> +  if (Object.keys(req.body).length === 0) return res.status(400).send({ message: 'Тело запроса пустое' });
Нужно исправить: Обработка ошибок должна быть централизованной. Валидация должна проходить уровнем выше

2020-02-11 15:46 UTC, zlocate commented
Пропущена ошибка на фронте: код и результат работы бека (ответ) не проверяются на фронте - бек возвращает ошибку удаления а на фронте элемент удаляется успешно, хотя фактически удаления не происходит.
Просьба исправить данную проблему

2020-02-11 17:25 UTC, zlocate commented on README.md
> +* Домен ackudryavcev.tk
Нужно исправить: по данному домену должен быть доступен бекенд-сервис, а не фронтенд

2020-02-13 09:33 UTC, ackudryavcev commented on models/card.js
> +const validator = require('validator');
иправил
const validate = require('validator');

2020-02-13 09:34 UTC, ackudryavcev commented on README.md
> +* Домен ackudryavcev.tk
не описал полностью
* Домен ackudryavcev.tk   фронтенд
* Домен api.ackudryavcev.tk бэкенд

2020-02-13 09:39 UTC, ackudryavcev commented on models/card.js
> +      validator: (v) => validate.isURL(v),
исправлено. выше отписал

2020-02-13 09:41 UTC, ackudryavcev commented on doteenv.env
> +NODE_ENV=production
при копировании не скопировал скрытые файлы, исправил gitignore скопировал, при новой заливке env  должен пропасть

2020-02-13 10:04 UTC, ackudryavcev commented on controllers/users.js
> +  if (Object.keys(req.body).length === 0) return res.status(400).send({ message: 'Тело запроса пустое' });
if (Object.keys(req.body).length === 0) {next(new req_err('Произошла ошибка при чтении списка пользователей')); return;}

2020-02-13 11:19 UTC, ackudryavcev commented on app.js
> +app.get('/crash-test', () => {
проделал еще раз все что указано в уроке Как сделать так, чтобы приложение работало всегда?
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ackudryavcev --hp /home/ackudryavcev

2020-02-13 11:26 UTC, ackudryavcev commented
Исправил критичные ошибки

2020-02-13 12:32 UTC, ackudryavcev commented
> Можно лучше: Фронтенд ходит на praktikum.tk вместо вашего бэка. Это точно то, что вы планировали? :)

ну сейчас в моей базе бэк пусто, была бы пустая страница, возможно не до конца понял задание, если не критично, возможно так оставить ?

2020-02-13 12:42 UTC, zlocate commented
@ackudryavcev в рамках данного задания размещать фронтенд на самом деле не требуется, поэтому помечаю как `можно лучше`, однако если вы указываете url фронта то по логике он должен вести на вашу реализацию бэка :)

2020-02-13 12:59 UTC, ackudryavcev commented
@zlocate   в итоге мне что то из критичных замечаний нужно исправлять для того, чтобы работа была принята ?

2020-02-16 10:03 UTC, merged